### ISSUE TITLE
Fix mix content warnings

### ISSUE THREAD

**Issue by kberzinch** [kberzinch/cs1331.org#2]
Site has moved to HTTPS which is causing errors when attempting to retrieve content from insecure origins.

**Comment by jgkamat** [comment]
Probably all you need to do is change [this](https://github.com/kberzinch/cs1331.org/blob/fc88bd7a3d9c376cb55ceca8cbf76d1309621aa9/index.php#L9) to the proxy.

**Comment by kberzinch** [comment]
Fixed in 55c1ac4eb438868a8ec560343112345106f2cbff

**Comment by kberzinch** [comment]
@jgkamat The line you linked can and should stay as is, I think. No reason routing that through the proxy.
